### ISSUE TITLE
新版本运行报错

### ISSUE THREAD

**Issue by 1336665** [purofle/Black-Cat-qqbot#8]
> PS C:\Black-Cat-qqbot-1.2.1> python main.py Traceback (most recent call last): 
File "main.py", line 14, in <module> 
from utils.utils import get_all_package_name File "C:\Black-Cat-qqbot-1.2.1\utils\utils.py", line 6, in <module> 
def get_all_package_name(path: str) -> list[str]: 
TypeError: 'type' object is not subscriptable

运行`v1.0`没有问题 但是后面的版本一直运行不了

**Comment by purofle** [comment]
请使用python3.9


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月28日(周六) 上午9:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [purofle/Black-Cat-qqbot] 新版本运行报错 (#8)




  
PS C:\Black-Cat-qqbot-1.2.1&gt; python main.py Traceback (most recent call last):
 File "main.py", line 14, in 
 from utils.utils import get_all_package_name File "C:\Black-Cat-qqbot-1.2.1\utils\utils.py", line 6, in 
 def get_all_package_name(path: str) -&gt; list[str]:
 TypeError: 'type' object is not subscriptable
  
运行v1.0没有问题 但是后面的版本一直运行不了
 
&mdash;
